spring:
  security:
    oauth2:
      resourceserver: #this app is protecting APIs, not logging users in with a browser, an OAuth2 resource server
        jwt: #incoming bearer tokens are JWTs
          issuer-uri: http://localhost:8443/realms/gateway  #trust tokens issued by this specific authorization server
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: registration-api
#              uri: http://localhost:8080
              uri: lb://REGISTRATION-API
              predicates:
                - Path=/api/v1/customers, /api/v1/customers/{customerId}, /api/v1/customers/me, /api/v1/customers/{customerId}/addresses/**, /api/v1/customers/{customerId}/phones/**, /api/v1/customers/{customerId}/status
            - id: scheduling-api
              uri: lb://SCHEDULING-API
              predicates:
                - Path=/api/v1/customers/{customerId}/tasks/**, /api/v1/admin/tasks

eureka:
  instance:
    hostname: localhost
    home-page-url: http://localhost:${server.port}/
    ip-address: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoint:
    gateway:
      access: read-only
  endpoints:
    web:
      exposure:
        include: gateway

logging:
  level:
    root: info
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: TRACE
    org.springframework.cloud.gateway: TRACE

server:
  port: 8880
