spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
some:
  property: dev-value

management:
  endpoint:
    env:
      show-values: always
      show-components: always
  endpoints:
    web:
      exposure:
        include: busrefresh,refresh,health,info,env


server:
  port: 8081