spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/registration
    username:
    password:
  jpa:
    database: POSTGRESQL
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
some:
  property: prod-value

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,env

server:
  port: 8082
