spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  mongodb:
    uri: ${MONGO_URI}
    database: ${MONGO_DATABASE}

  kafka:
    bootstrap-servers: localhost:9092,localhost:9094,localhost:9096
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      acks: all #no data loss
      properties:
        enable:
          idempotence: true # avoids duplicate messages even if network glitch happens (safe tries)
        max:
          in:
            flight:
              requests:
                per:
                  connection: 5 #how many unacknowledged requests can exist simultaneously per connection
        delivery:
          timeout:
            ms: 120000 #total amount Kafka Producer will try to deliver a message before failing permanently
        linger:
          ms: 0 # sends immediately, no batching delay (latency vs throughput)
        request:
          timeout:
            ms: 30000 #broker has 30s to respond to a single request
server:
  port: 8085

customer:
  url: http://localhost:8082 #points to registration-api-prod port 8082

management:
  endpoint:
    env:
      show-values: always
      show-components: always
  endpoints:
    web:
      exposure:
        include: busrefresh,refresh,health,info,env
some:
  property: prod-value

client:
  type: feign

logging:
  level:
    root: INFO