spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  mongodb:
    uri: ${MONGO_URI}
    database: ${MONGO_DATABASE}

  kafka:
    bootstrap-servers: host.docker.internal:9092,host.docker.internal:9094,host.docker.internal:9096
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      acks: all #no data loss
      properties:
        enable:
          idempotence: true # avoids duplicate messages even if network glitch happens (safe tries)
        max:
          in:
            flight:
              requests:
                per:
                  connection: 5 #how many unacknowledged requests can exist simultaneously per connection
        delivery:
          timeout:
            ms: 120000 #total amount Kafka Producer will try to deliver a message before failing permanently
        linger:
          ms: 0 # sends immediately, no batching delay (latency vs throughput)
        request:
          timeout:
            ms: 30000 #broker has 30s to respond to a single request

#customer:
#  url: http://localhost:8081 #points to registration-api-dev port 8081

management:
  endpoint:
    env:
      show-values: always
      show-components: always
  endpoints:
    web:
      exposure:
        include: busrefresh,refresh,health,info,env

client:
  type: feign

eureka:
  instance:
    hostname: localhost
    ip-address: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

some:
  property: dev-value

server:
  port: 8084

logging:
  level:
    root: INFO