spring:
  application:
    name: configserver

#  profiles:
#    active: native

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10000
    requested-heartbeat: 30

  cloud:
    bus:
      destination: springCloudBus

    config:
      server:
        native:
          search-locations: /config

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8888